[email]
server = "server"
username = "user"
password = "mypassword"
port = 995  # POP3

[smtp]
server = "server"
port = 587  # STARTTLS
username = "user"
password = "mypassword"
from_address = "no-reply@unimusik-goettingen.de"
from_name = "Anmeldesystem Probenwochenende Unimusik"
additional_info = "Bei Fragen schreibt uns gerne unter pwe@unimusik-goettingen.de"

[bank]
account_name = "Förderverein Göttinger Universitätschor und -orchester e. V."
iban = "DE42260500010000003301"
bic = "NOLADE21GOE"
bank_name = "Sparkasse Göttingen"  # Optional
enable_qr = true  # Optional, defaults to true
